Fix webpack config
1.
TypeError: _webpack2.default.optimize.OccurenceOrderPlugin is not a constructor

2.
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'.

3.
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel'.